### ISSUE TITLE
low priority suggestions: locate structure command and tpbiome option list

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#5]
Just some command quality of life features that don't require high priority.
- Some sort of locate command to find the nearest structures of Gold Dungeons, End Strongholds, and such. The command shows the coords for the structures. Though I understand how it may be difficult due to how these structures must be generated first in order to be recorded, so possibly a world generation plugin may be necessary in order for this to be effective.
- /betterend version doesn't do anything. Though may just not be implemented yet
- Make it so /betterend tpbiome gives a list of options such as just writing /betterend tpbiome returns with /betterend tpbiome {end,shattered_end,void,aether,aether_highlands}

**Comment by dfsek** [comment]
Locate would be quite difficult to do because of how I currently have structures implemented. I am working on a complete rewrite of structure generation that will be much more performant and remove the dependency on WorldEdit, so I can try to implement that alongside the new method.

Version simply hasn't been implemented, I'll do that in the next release

I am eventually going o add proper tab completion to all commands and subcommands.

**Comment by dfsek** [comment]
Commands are going to be reworked in 2.1, implementing all but the locate command. Due to the way structures are generated, there is no way to know for sure that a structure will generate in a certain location without first generating the location.

**Comment by DeathShadez** [comment]
Alright

**Comment by dfsek** [comment]
Added in 3.0.0
